### PR TITLE
Use injection all the way down

### PR DESCRIPTION
**Pull request by ajs6f**

### CODE REVIEW

**Comment by ajs6f** [comment]
@gregjan If you buy my plan about injection, merge this, and we can wait for @acoburn to merge https://github.com/trellis-ldp/trellis/pull/405.

**Comment by ajs6f** [comment]
Oh, hang on, might have one more commit (I always do this, don't I?)!

**Comment by ajs6f** [comment]
There ya go, ready for review.

**Comment by ajs6f** [comment]
@gregjan If you can merge this, I can merge https://github.com/trellis-ldp/trellis-cassandra/pull/65 and you can move forward with WebAC-equipped testing.

**Comment by ajs6f** [comment]
@gregjan Just pinging on this-- are you waiting on anything from me?

**Comment by gregjan** [comment]
I'm getting ready to do some build/test cycles. Back in the office today after a long weekend.

**Comment by ajs6f** [comment]
Thank you! Hope it was a lovely Mem Day for you.

**Comment by gregjan** [comment]
It was. (BTW, I also somehow missed that my own branch was the PR target here, or I would have done it sooner..)

**Comment by ajs6f** [comment]
NP-- PRs to PRs are always a little weird.

**Pull request merged**
